class ClienteModelo{
    constructor(){
        this.nombre =datoNombre;
        this.Apellido = datoAellido;
        this.Rol =datoRol;
    }
    Get_nombre(){
        return this.nombre;
    }
    Set_nombre(nuevo_dato_nombre){
        this.nombre=nuevo_dato_nombre;

    }
    Get_Apellido(){
        return this.Apellido;
    }
    Set_Apellido(nuevo_dato_Apellido){
        this.Apellido=nuevo_dato_Apellido;

    }
    Get_Rol(){
        return this.Rol;
    }
    Set_Apellido(nuevo_dato_Rol){
        this.Rol=nuevo_dato_Rol;

    }
}